/*
************************************************************
* COMPILERS COURSE - Algonquin College
* Code version: Fall, 2023
* Author: TO_DO
* Professors: Paulo Sousa
************************************************************
=---------------------------------------=
|  COMPILERS - ALGONQUIN COLLEGE (F23)  |
=---------------------------------------=
|              ....                     |
|          ........::.::::::.           |
|        .:........::.:^^^~~~:          |
|        :^^::::::^^^::^!7??7~^.        |
|       .:^~~^!77777~~7?YY?7??7^.       |
|       :.^~!??!^::::^^~!?5PY??!~.      |
|       ~!!7J~.:::^^^^~!!~~?G5J?~       |
|       :^~?!~7?Y57^^?PP5YJ!J5Y?:       |
|       .~!!.:^!7!:.:7JYYJ7~7Y7^        |
|       .~77..    . .~^:^^^~7?:         |
|       .^!^~:::.:^!7?~^~!77J:          |
|        ^^!Y~^^^^~?YJ77??7JJ^          |
|       .^7J?~^~~^~7??7??7JY?~:         |
|        ::^^~^7?!^~~!7???J?J7~:.       |
|         ^~~!.^7YPPPP5Y?7J7777~.       |
|        ..:~..:^!JPP5YJ?!777!^.        |
| .~?JJJJJJJJJJYYYYYPPPPPPPPPPPP5PPYY~  |
|  :!Y5GGG.___ YYYYYY__._.PPGGGGGG5!.   |
|   :!Y5G / __| ___ / _(_)__ _ PGP5.    |
|    :~75 \__ \/ _ \  _| / _` | 5?.     |
|     7~7 |___/\___/_| |_\__,_| Y5?.    |
|    .^~!~.....................P5YY7.   |
|   .:::::::::::::?JJJJYYYYYYYYYJJJJ7.  |
|                                       |
=---------------------------------------=
*/

/*
************************************************************
* File name: MainScanner.c
* Compiler: MS Visual Studio 2022
* Course: CST 8152 – Compilers, Lab Section: [011, 012]
* Assignment: A22, A32.
* Date: May 01 2022
* Purpose: This file is the main code for Scanner (A22)
* Function list: (...).
************************************************************
*/

/*
 *.............................................................................
 * ADVICE 1:
 * Please check the "TODO" labels to develop your activity.
 *
 * ADVICE 2: Preprocessor directives
 * The #define _CRT_SECURE_NO_WARNINGS should be used in MS Visual Studio projects
 * to suppress the warnings about using "unsafe" functions like fopen()
 * and standard sting library functions defined in string.h.
 * The define directive does not have any effect on other compiler projects
 * (Gcc, VSCode, Codeblocks, etc.).
 *.............................................................................
 */

#define _CRT_SECURE_NO_WARNINGS

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

#ifndef COMPILERS_H_
#include "Compilers.h"
#endif

#ifndef BUFFER_H_
#include "Reader.h"
#endif

#ifndef SCANNER_H_
#include "Scanner.h"
#endif

 /*check for ANSI C compliancy */
#define ANSI_C 0
#if defined(__STDC__)
#undef ANSI_C
#define ANSI_C 1
#endif

/*
 * -------------------------------------------------------------
 *  Global vars and External vars
 * -------------------------------------------------------------
 */

 /* Global objects - variables (used in other codes as external) */
extern BufferPointer stringLiteralTable; /* String literal table */
extern GoLite_intg errorNumber;          /* Run-time error number */

/* External objects */
extern GoLite_intg line; /* Current line number of the source code */
extern Token tokenizer(void);

/*
 * -------------------------------------------------------------
 *  Function declarations
 * -------------------------------------------------------------
 */
void printScannerError(GoLite_string fmt, ...);
void displayScanner(BufferPointer ptrBuffer);
GoLite_long getScannerFilesize(GoLite_string fname);
void printToken(Token t);
/*
************************************************************
 *  Scanner Main function
 * Parameters:
 *   argc / argv = Parameters from command prompt
 * Return value:
 *	Success operation.
 ***********************************************************
 */

GoLite_intg mainScanner(GoLite_intg argc, GoLite_string* argv) {
    BufferPointer sourceBuffer; /* Pointer to input source buffer */
    FILE* fileHandler;          /* File handler for source file */
    Token currentToken;         /* Token generated by scanner */
    GoLite_intg loadSize = 0;   /* Size of file loaded into buffer */

    // Handling command line arguments for source file name
    if (argc <= 2) {
        printScannerError("Runtime error at line %d in file %s", __LINE__, __FILE__);
        printScannerError("Missing source file name. Usage: <Program> <SourceFile>");
        exit(EXIT_FAILURE);
    }

    // Debug mode information
    printf("[Debug mode: %d]\n", DEBUG);

    // Create a source code input buffer
    sourceBuffer = readerCreate(READER_DEFAULT_SIZE, READER_DEFAULT_INCREMENT, MODE_MULTI);
    if (sourceBuffer == NULL) {
        printScannerError("Could not create source buffer");
        exit(EXIT_FAILURE);
    }

    // Open the source file
    if ((fileHandler = fopen(argv[2], "r")) == NULL) {
        printScannerError("Cannot open file: %s", argv[2]);
        exit(EXIT_FAILURE);
    }

    // Load the source file into the input buffer
    printf("Reading file %s... Please wait\n", argv[2]);
    loadSize = readerLoad(sourceBuffer, fileHandler);
    fclose(fileHandler);

    // Check for errors during file loading
    if (loadSize == READER_ERROR) {
        printScannerError("Error in loading buffer.");
    }

    // Display source buffer content
    if ((loadSize != READER_ERROR) && (loadSize != 0)) {
        if (readerAddChar(sourceBuffer, READER_TERMINATOR)) {
            displayScanner(sourceBuffer);
        }
    }

    // Create string literal table
    stringLiteralTable = readerCreate(READER_DEFAULT_SIZE, READER_DEFAULT_INCREMENT, MODE_ADDIT);
    if (stringLiteralTable == NULL) {
        printScannerError("Could not create string literals buffer");
        exit(EXIT_FAILURE);
    }

    // Initialize scanner and process tokens
    if (startScanner(sourceBuffer)) {
        printScannerError("Empty program buffer - scanning canceled");
        exit(EXIT_FAILURE);
    }

    printf("Scanning source file...\n");
    printf("Token\t\tAttribute\n");
    printf("----------------------------------\n");
    do {
        currentToken = tokenizer();
        printToken(currentToken);
    } while (currentToken.code != SEOF_T);

    // Print string literal table
    printf("\nPrinting string table...\n");
    printf("----------------------------------\n");
    if (readerGetPosWrte(stringLiteralTable)) {
        readerPrint(stringLiteralTable);
    }
    printf("----------------------------------\n");

    // Cleanup
    readerRestore(sourceBuffer);
    readerRestore(stringLiteralTable);
    sourceBuffer = stringLiteralTable = NULL;
    printScannerData(scData);

    // Additional options
    if (argv[3] != NULL && *argv[3] == 'l') {
        printf("The number of lines is: %d\n", line);
    }

    return EXIT_SUCCESS;
}


/*
************************************************************
 *  Error printing function with variable number of arguments
 *  Params: Variable arguments, using formats from C language.
 *	 - Internal vars use list of arguments and types from stdarg.h
 *   - NOTE: The format is using signature from C Language
***********************************************************
*/

void printScannerError(GoLite_string fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    vfprintf(stderr, fmt, ap);
    va_end(ap);

    /* Move to new line if not already included */
    if (strchr(fmt, '\n') == NULL) {
        fprintf(stderr, "\n");
    }
}

/*
************************************************************
 * The function displays buffer contents
 * Param:
 *		- Scanner to be displayed.
 ***********************************************************
 */

void displayScanner(BufferPointer ptrBuffer) {
    printf("\nPrinting buffer parameters:\n\n");
    printf("The capacity of the buffer is:  %d\n", readerGetSize(ptrBuffer));
    printf("The current size of the buffer is:  %d\n", readerGetPosWrte(ptrBuffer));
    printf("\nPrinting buffer contents:\n\n");
    readerRecover(ptrBuffer);
    readerPrint(ptrBuffer);
}

/*
 ************************************************************
 * The function gets size of scanner file
 * Param:
 *	- Filename
 * Return:
 *	- Size of the file
 ***********************************************************
 */

GoLite_long getScannerFilesize(GoLite_string fname) {
    FILE* fileInput;
    GoLite_long fileLength;

    fileInput = fopen(fname, "r");
    if (fileInput == NULL) {
        printScannerError("Cannot open file: %s", fname);
        return 0L;
    }

    fseek(fileInput, 0L, SEEK_END);
    fileLength = ftell(fileInput);
    fclose(fileInput);
    return fileLength;
}